import { z } from "zod";

const finite = z.coerce.number().finite();

export const armorParamRowSchema = z.object({
  ID: z.coerce.number().int().nonnegative(),
  Name: z.string(),
  protectorCategory: z.coerce.number().int(),
  iconIdM: z.coerce.number().int().nonnegative(),
  weight: finite.nonnegative(),
  toughnessCorrectRate: finite.nonnegative(),
  neutralDamageCutRate: finite.nonnegative(),
  slashDamageCutRate: finite.nonnegative(),
  blowDamageCutRate: finite.nonnegative(),
  thrustDamageCutRate: finite.nonnegative(),
  magicDamageCutRate: finite.nonnegative(),
  fireDamageCutRate: finite.nonnegative(),
  thunderDamageCutRate: finite.nonnegative(),
  darkDamageCutRate: finite.nonnegative(),
  resistPoison: z.coerce.number().int().nonnegative(),
  resistDisease: z.coerce.number().int().nonnegative(),
  resistBlood: z.coerce.number().int().nonnegative(),
  resistFreeze: z.coerce.number().int().nonnegative(),
  resistSleep: z.coerce.number().int().nonnegative(),
  resistMadness: z.coerce.number().int().nonnegative(),
  resistCurse: z.coerce.number().int().nonnegative(),
  residentSpEffectId: z.coerce.number().int(),
  residentSpEffectId2: z.coerce.number().int(),
  residentSpEffectId3: z.coerce.number().int(),
});

export type ArmorParamRow = z.infer<typeof armorParamRowSchema>;

const multiplier = z.preprocess((value) => value === "" ? 1 : value, z.coerce.number().finite().nonnegative());

export const armorEffectRowSchema = z.object({
  ID: z.coerce.number().int().nonnegative(),
  addLifeForceStatus: z.coerce.number().int(),
  addWillpowerStatus: z.coerce.number().int(),
  addEndureStatus: z.coerce.number().int(),
  addStrengthStatus: z.coerce.number().int(),
  addDexterityStatus: z.coerce.number().int(),
  addMagicStatus: z.coerce.number().int(),
  addFaithStatus: z.coerce.number().int(),
  addLuckStatus: z.coerce.number().int(),
  maxHpRate: multiplier,
  maxMpRate: multiplier,
  maxStaminaRate: multiplier,
  equipWeightChangeRate: multiplier,
  staminaRecoverChangeSpeed: finite.default(0),
  artsConsumptionRate: multiplier,
  magicConsumptionRate: multiplier,
  miracleConsumptionRate: multiplier,
  neutralDamageCutRate: multiplier,
  magicDamageCutRate: multiplier,
  fireDamageCutRate: multiplier,
  thunderDamageCutRate: multiplier,
  darkDamageCutRate: multiplier,
  changePoisonResistPoint: finite,
  changeDiseaseResistPoint: finite,
  changeBloodResistPoint: finite,
  changeFreezeResistPoint: finite,
  changeSleepResistPoint: finite,
  changeMadnessResistPoint: finite,
  changeCurseResistPoint: finite,
  changeHpEstusFlaskCorrectRate: multiplier,
  changeMpEstusFlaskCorrectRate: multiplier,
  invocationConditionsStateChange1: z.coerce.number().int(),
  cycleOccurrenceSpEffectId: z.coerce.number().int(),
  atkOccurrenceSpEffectId: z.coerce.number().int().default(-1),
  effectEndurance: finite,
  atkEnemyDmgCorrectRate_Physics: multiplier,
  atkEnemyDmgCorrectRate_Magic: multiplier,
  atkEnemyDmgCorrectRate_Fire: multiplier,
  atkEnemyDmgCorrectRate_Thunder: multiplier,
  atkEnemyDmgCorrectRate_Dark: multiplier,
  defEnemyDmgCorrectRate_Physics: multiplier.default(1),
  defEnemyDmgCorrectRate_Magic: multiplier.default(1),
  defEnemyDmgCorrectRate_Fire: multiplier.default(1),
  defEnemyDmgCorrectRate_Thunder: multiplier.default(1),
  defEnemyDmgCorrectRate_Dark: multiplier.default(1),
  conditionHp: finite,
  motionInterval: finite,
  changeHpPoint: finite,
  changeHpRate: finite.default(0),
  changeMpRate: finite.default(0),
  hearingSearchEnemyRate: multiplier,
  targetPriority: finite,
  physicsAttackPower: finite,
  magicAttackPower: finite,
  fireAttackPower: finite,
  thunderAttackPower: finite,
  darkAttackPower: finite,
  behaviorId: z.coerce.number().int(),
  physicsAttackRate: multiplier,
  magicAttackRate: multiplier,
  fireAttackRate: multiplier,
  thunderAttackRate: multiplier,
  darkAttackRate: multiplier,
  physicsAttackPowerRate: multiplier,
  magicAttackPowerRate: multiplier.optional(),
  fireAttackPowerRate: multiplier.optional(),
  thunderAttackPowerRate: multiplier.optional(),
  darkAttackPowerRate: multiplier.optional(),
  saAttackPowerRate: multiplier.optional(),
  stateInfo: z.coerce.number().int(),
  poizonAttackPower: finite,
  diseaseAttackPower: finite,
  bloodAttackPower: finite,
  curseAttackPower: finite,
  freezeAttackPower: finite,
  sleepAttackPower: finite,
  madnessAttackPower: finite,
});

export type ArmorEffectRow = z.infer<typeof armorEffectRowSchema>;

export const armorBehaviorRowSchema = z.object({
  ID: z.coerce.number().int().nonnegative(),
  refType: z.coerce.number().int(),
  refId: z.coerce.number().int(),
});

export const armorBulletRowSchema = z.object({
  ID: z.coerce.number().int().nonnegative(),
  hitRadius: finite,
  spEffectId0: z.coerce.number().int(),
});

export type ArmorBehaviorRow = z.infer<typeof armorBehaviorRowSchema>;
export type ArmorBulletRow = z.infer<typeof armorBulletRowSchema>;
