import { z } from "zod";

const multiplierFromCsv = z.preprocess(
  (value) => value === "" ? 1 : value,
  z.coerce.number().finite().nonnegative(),
);

export const talismanEffectParamRowSchema = z.object({
  ID: z.coerce.number().int().nonnegative(),
  Name: z.string(),
  maxHpRate: multiplierFromCsv,
  maxMpRate: multiplierFromCsv,
  maxStaminaRate: multiplierFromCsv,
  equipWeightChangeRate: multiplierFromCsv,
  changePoisonResistPoint: z.coerce.number().int(),
  changeDiseaseResistPoint: z.coerce.number().int(),
  changeBloodResistPoint: z.coerce.number().int(),
  changeFreezeResistPoint: z.coerce.number().int(),
  changeSleepResistPoint: z.coerce.number().int(),
  changeMadnessResistPoint: z.coerce.number().int(),
  changeCurseResistPoint: z.coerce.number().int(),
  itemDropRate: z.coerce.number().finite(),
  soulRate: multiplierFromCsv,
  changeMagicSlot: z.coerce.number().int(),
  staminaRecoverChangeSpeed: z.coerce.number().finite(),
  toughnessDamageCutRate: multiplierFromCsv,
  artsConsumptionRate: multiplierFromCsv,
  magicConsumptionRate: multiplierFromCsv,
  extendLifeRate: multiplierFromCsv,
  dexterityCancelSystemOnlyAddDexterity: z.coerce.number().int(),
  changeHpEstusFlaskCorrectRate: multiplierFromCsv,
  changeMpEstusFlaskCorrectRate: multiplierFromCsv,
  motionInterval: z.coerce.number().finite(),
  changeHpPoint: z.coerce.number().finite(),
  changeHpRate: z.coerce.number().finite(),
  changeMpPoint: z.coerce.number().finite(),
  staminaAttackRate: multiplierFromCsv,
  guardStaminaMult: multiplierFromCsv,
  conditionHp: z.coerce.number().finite(),
  conditionHpRate: z.coerce.number().finite(),
  bowDistRate: z.coerce.number().finite(),
  accumuOverVal: z.coerce.number().finite(),
  effectEndurance: z.coerce.number().finite(),
  cycleOccurrenceSpEffectId: z.coerce.number().int(),
  invocationConditionsStateChange1: z.coerce.number().int(),
  fallDamageRate: multiplierFromCsv,
  targetPriority: z.coerce.number().finite(),
  hearingSearchEnemyRate: multiplierFromCsv,
  stateInfo: z.coerce.number().int(),
  vfxId: z.coerce.number().int(),
  addLifeForceStatus: z.coerce.number().int(),
  addWillpowerStatus: z.coerce.number().int(),
  addEndureStatus: z.coerce.number().int(),
  addStrengthStatus: z.coerce.number().int(),
  addDexterityStatus: z.coerce.number().int(),
  addMagicStatus: z.coerce.number().int(),
  addFaithStatus: z.coerce.number().int(),
  addLuckStatus: z.coerce.number().int(),
  neutralDamageCutRate: multiplierFromCsv,
  magicDamageCutRate: multiplierFromCsv,
  fireDamageCutRate: multiplierFromCsv,
  thunderDamageCutRate: multiplierFromCsv,
  darkDamageCutRate: multiplierFromCsv,
  defEnemyDmgCorrectRate_Physics: multiplierFromCsv,
  defEnemyDmgCorrectRate_Magic: multiplierFromCsv,
  defEnemyDmgCorrectRate_Fire: multiplierFromCsv,
  defEnemyDmgCorrectRate_Thunder: multiplierFromCsv,
  defEnemyDmgCorrectRate_Dark: multiplierFromCsv,
  atkEnemyDmgCorrectRate_Physics: multiplierFromCsv,
  atkEnemyDmgCorrectRate_Magic: multiplierFromCsv,
  atkEnemyDmgCorrectRate_Fire: multiplierFromCsv,
  atkEnemyDmgCorrectRate_Thunder: multiplierFromCsv,
  atkEnemyDmgCorrectRate_Dark: multiplierFromCsv,
  physicsAttackRate: multiplierFromCsv,
  magicAttackRate: multiplierFromCsv,
  fireAttackRate: multiplierFromCsv,
  thunderAttackRate: multiplierFromCsv,
  darkAttackRate: multiplierFromCsv,
});

export type TalismanEffectParamRow = z.infer<typeof talismanEffectParamRowSchema>;
